# inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Style/RedundantFileExtensionInRequire:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# Performance/Readability
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
